package exceptions

import "testing"

func TestVoid(t *testing.T) {
	return
}
